name = "Benchmark"
uuid = "82c275cb-58a2-4ee6-a965-cd7cf8f0542c"
authors = ["Roger-luo"]
version = "0.1.0"

[deps]
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[compat]
julia = "1.4.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
